version: "3.8"
services:
  users-service:
    build:
      context: ./users
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "jdbc:postgresql://host.docker.internal:5434/my_finances_users_db"
        DATABASE_USERNAME: "postgres"
        DATABASE_PASSWORD: "postgres"
    image: my_finances_users_service
    env_file: ./users/environments/dev-docker.env
    ports:
      - "8083:8083"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        USER_SERVICE_URL: "http://host.docker.internal:8083/api/"
    image: my_finances_api_gateway
    env_file: ./api-gateway/environments/dev-docker.env
    ports:
      - "8082:8082"
