version: "3.8"
services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
